name: baby_memory_collage_app
description: A Flutter app for baby milestone and holiday photo collages.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.1
  google_sign_in: ^5.4.2
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.2.2
  provider: ^6.0.5
  image_picker: ^0.8.7+5
  permission_handler: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: - assets/images/
